### PR TITLE
Adding images and status

### PR DESCRIPTION
**Pull request by BookCatKid**
Added some functionality for getting images, and the status svg. (I didn't do rewards as I don't really understand them). I also added an html file used for viewing the downloaded csv.
DO NOT merge this yet, the documentation is not finished (the code could be improved too)

### CODE REVIEW

**Comment by BookCatKid** [comment]
FIXED:
	~~BUG: Songs marked as new or re-entry show up as the awards svg~~

**Comment by jsubroto** [comment]
Thanks @BookCatKid! Do you mind removing your code comments and also to serve the page from the root path `/`? You can use `do_GET()`. I also think you can rename the html file to `index.html` since there's only one page.

**Comment by BookCatKid** [comment]
Sure! I'll get right on it.

**Comment by BookCatKid** [comment]
Alright I finished removing comments and renameing to index.html

**Comment by jsubroto** [comment]
Thanks!

**Pull request merged**
